### ISSUE TITLE
About active mode of Firetrap

### ISSUE THREAD

**Issue by omikuji** [koenw/firetrap#45]
Hello Koenw!

[This LIST command](https://github.com/koenw/firetrap/blob/master/src/server.rs#L800-L810) is implemented. But, [this is](https://github.com/koenw/firetrap/blob/master/src/server.rs#L361-L391) not implemented.

Given the above code, Do Firetrap only assume connection in passive mode?

Also, are you planning to support connections other than passive mode (for example an active mode) in the future?

Thank you :)

**Comment by koenw** [comment]
Hi omikuji:)

You're right, at the moment firetrap only supports passive mode. There are also at the moment no support for other connection modes.

Do you have a need for e.g. active mode?

**Comment by omikuji** [comment]
Sorry for my late reply :'-(

I wanted to know the future direction of firetrap.
I agree with not implementing active mode!

Thank you for your continuous support!!
